### ISSUE TITLE
Community Support

### ISSUE THREAD

**Issue by mnzone-dev** [SuB1X-Coin/proposals#3]
## Requested Funds

* One time proposal of **50** SUB1X (11.5% from the monthly governance budget)
* **0.05** SUB1X to cover the proposal submission and transfer fees to winners

Paid to my address `ZZgxu9G4pehp7DP7mE8khkXNGTucKow53i` and then distributed as described below.

## Describe your proposal

The coins will be distributed to five users that are the most active and helpful in the community.
For example moderators, tech support in Discord, Bitcointalk, Proposals repo, etc

If this proposal passes, we can have a Discord announcement with the nominees. Each will have an emoji number attached. Top five will be picked based on the number of emoji votes. 

The winners will receive a 10 SUB1X reward for their dedication to the project and community.
They could also receive a special Discord role(Community Superstar, or similar) for the next month.
The aim is to reward good behavior with a good amount of SUB1X coins!

If this is a success, we can have it as a monthly proposal, starting from the next budget cycle.

## Proposal creator Discord user:
`mn.zone_dev#7125`

**Comment by P3shy** [comment]
Great idea to get the team involved with the community a bit more and I believe this is healthy competition which will contribute greatly to the growth of the project. Giving top 5 most active community members equal amount of reward will be more beneficial. I don't like the idea of spreading the rewards unequally. There are some members which help out behind the scene by guiding through their masternode setup. Thank you once again for a such a great proposal. I am for it.

**Comment by dojo90** [comment]
I don't think this is a good idea. Does not every employee gets an allowance already?

**Comment by mnzone-dev** [comment]
There are no employees @dojo90. You could be one of the winners if you dedicate time and the community wants to incentivize you for your efforts.

@willdono what's your take here, any exclusions from the nominees for this?

**Comment by SuB1X-Coin** [comment]
I personally think that 11.5% of the governance budget is too high. Also, the incentives are not concrete enough to increase community participation. A better proposition would be for more more volunteers to step up as mod. We can then have a committee in place to judge the quality and effort given by each moderator. We could then use a sliding pay scale to payout each individual mod.

**Comment by aaroque** [comment]
IMHO as MNZone says 10 Sub1x for those selected by the community vote due to their participation, effort and help to other members in any possible way is fair enough for a decent start that's why I'm 100% positive for this proposal. Once we reach higher levels on the coin price we can lower the amount of coins towards those winners once again if the vote is positive, if not we just leave it like it is and the fight and future of the project will be Fantastic because no longer will be $150 for the winning price, 5-10k could be really possible. 
If I were a winner I would never sell those earn coins so cheap, instead will buy more to do another MN. My position of course. 
We're only 500 members on telegram and think like 730 on discord already, we're still starting, a lot of problems were left behind us. We need to focus in the future and a better start for sure will be pay a decent amount to those who deserve it and motivate others to join that path. Will be really nice to watch. My 2 cents ofc.

**Comment by P3shy** [comment]
@dojo90 No one here is employed by SUB1X just yet. Everyone has been doing their part for the good of the community. Generous donations have been made to me by the team but there is not regular payments as of yet.

**Comment by dojo90** [comment]
Well, then I take my answer back, because I did not know that.
Wouldn't it be better if you paid out an equal share to all "employees"? Not depending on how the community decides who should get the reward. Or is meant to be a community currency without any salaried employees?

**Comment by P3shy** [comment]
@Klaud07 It would not be for the "chatterbox" of the team, it would be to those who help the community out with masternode setup and to those who take an active part in community discussions. What do you think will be solved if a community is not actively sharing ideas and engaging in conversations. We are a relatively small crypto community correct, but within the past month or so we have grown by 60 to 70 members, which is a success in my opinion. It will take time and hard work from everyone's part and it would only be fair to give back to those who put in the time to help the community grow. Please note that those who hold the coins and take an active part in the community are also the ones who are least likely to sell the coins because they believe in the project!

**Comment by Klaud07** [comment]
@P3shy so share ideas, what's the problem, I do exactly that. We will discuss this completely free of charge, because we (those to whom the project is interested) do this for the sake of project development, and not for the sake of reward in the form of coins for messages. I do not understand this at all, you propose to stimulate activity, for what? All this is not good, it's like writing comments for money in online stores, one hypocrisy.

**Comment by P3shy** [comment]
@Klaud07 Activity does not require money at all and communicating doesn't either. Time does. Bringing a community together requires time, helping people set up masternodes requires time, replying to private messages requires time. Yeah it's all fun to pop in once or twice a day just to say hi for a good 5 minutes or so then leave, but to those who spend hours replying and helping people do deserve reward. This is the reason why I am for it.

**Comment by Klaud07** [comment]
@P3shy I'm pretty actively involved in discussions on the forum and Telegram ( though I took a pause) and I want to note that we cope. All who need help get it from those who went to say Hello as you say. At the moment, we do not need 24/7 support, I agree that we can reward those who create something for the project, such as manuals for setting/installing anything (I'm talking about Francois), but not for activity.

**Comment by P3shy** [comment]
@Klaud07 You are right to some extent mate. Francois is of great help! Learnt how to set up my first masternode from him. I think a community which is active does bring in more investors but if I being completely honest I would much rather have the funds being spent on getting onto newer exchanges with more trade volume. People are selling SUB1X cheap because when bills need to be paid they need the money quickly. But I am for this proposal, at the end of the day the community as a whole decides.

**Comment by Klaud07** [comment]
@P3shy This is what I said, than to scatter coins for activity, it is better to try to build an interesting project that attracted people, and as I wrote in the telegram today, we need to get to the CMC and a good exchange, I generally proposed to hold a mini ICO for the project, and you and Willdono hope can read my ideas

**Comment by Klaud07** [comment]
I decided to copy my ideas here:
I also wanted to suggest an idea for lending the project, i.e. we need a exchange with a good volume, but we can not allow a dump of coins and most likely they (coins) will not be enough. What do I suggest:
1. Make a fund, some percentage of our awards will go to the project fund, but it will not be all fast, therefore, point 2:
2. We can conduct a survey of who is ready to buy coins at the current exchange rate (possibly + bonus), but receive them later (possibly in 1-12 months).
3. We have 450 nodes + people who are at POS, if everyone invests 0.1 BTC, we get about 45 BTC, we can get a listing on a good exchange, and for investment 0.1 BTC each will receive ~ 54 coins (today's rate) Sub1x after some number of months, but later 54 coins will cost much more than 0.1 BTC, you can call it miniICO for the community.
The figures are approximate, this can all be discussed, here the main it is idea.

**Comment by mnzone-dev** [comment]
These tickets are where we brainstorm and polish the proposals in order to have the highest impact possible. Accepting or rejecting is the job of the masternode owners with the votes. 

For the 45 BTC idea:
Majority of investors in this coin are in negative equity already. The community is paramount and we can list on bigger exchange free of charge, by having a big and active community. On the other extreme, we could be on Cryptopia after 25BTC listing fee and nobody cares. Automatic delisting in the future for lack of volume.

Let me give an example. Ravencoin, hit almost 200 BTC trading volume in a single day last week on.... on.... crypto-bridge  🚀 
matching the coin with the highest volume on Cryptopia that day, ETN. I can find 100 coins on cryptopia, that together don't reach that volume. And if we ever have to do a coin-swap on cryptopia, bye bye listing.

You can create a question only type proposal asking for the minimum amount, `0.04` SUB1X if I remember right. MN owners will vote yes/no and see what's the sentiment.

The direction where I would like to look into is adoption and utility of SUB1X.

**Comment by Klaud07** [comment]
@mnzone-dev To pay for listing on Cryptopia 25 BTC is suicide, this exchange is inferior even to the decentralized exchange iDex by the volume of trading. We need to get to the CMC as soon as possible, because most people do not have a lot of time, they go to the CMC and immediately see if it is worth studying the project further, if the project is not there, this is a big minus. Secondly, I am sure that the exchange with a large audience will help to attract interest in the project. Cryptobridge in terms of sales is not even in the top 100 of all exchanges, I'm sure that the audience is very low.

**Comment by P3shy** [comment]
@Klaud07 You are right it would help, but not significantly. Most people are not comfortable investing in projects with low market capital. We need a solid plan for what lays ahead and we need the community to do their part by inviting as many people as they know over. We could do more cross promotional stuff too which would help but from previous result the members gained wasn't high enough. We gained about 15 to 20 members in the first week of the shout out but that was it.

**Comment by Klaud07** [comment]
@P3shy Oh, I'm really surprised, apparently in different countries on differently relate to investing. For example, in Russia, on the contrary, investors are attracted by low capitalization and we are very reluctant to enter projects with bloated capitalization. The second point is that we can replenish our community for 10,000 participants literally in the course of a week just by launching the airdrop, but I'm not sure that this will do any good, it's more to the detriment ... I'm very impressed with the Solaris project, which regularly holds short bountys on the forum. They do not pay much, for example ~ $ 5 a week, for Twitter bounty and people willingly participate, install wallets on their computers, someone enters the project, thus it is possible to expand the community. But in order to hold such events, more news is needed. I mean, you must first prepare a news database, then to disseminate it widely. We don't have a lot of news and it's a problem and they (news) didn't get any distribution.

**Comment by mnzone-dev** [comment]
Thank you everyone for the feedback.
In a truly decentralized manner, MN owners will now vote with Yes/No on this proposal.

I merged it in the `final` directory of the repository:
`https://github.com/SuB1X-Coin/proposals/blob/master/final/CommunitySupportMay.md`

and I will use this short URL in the proposal submission:
`https://git.io/vhTpu`

**Comment by ghost** [comment]
Chaps, this has been minted by the blockchain as can be seen here:
http://explorer.sub1x.org/tx/563ace470ae6cfbf87379ebeb8c80e44790839329d73897fbf1ad0df49f20efe

In order to deliver this proposal, I scanned discord channels for active participants in the main channels (#general, #masternodes, #support). I came up with these nominations:

```
MEE6#4876  :)
MrsMasternode#3394
PatHeyman#7056
PzYcO#0420
Roque#6904
TheWatchers1456#1895
Wajito#6774
```

Please mention other users that should be in the voting list for the five 10 SUB1X prices. I didn't look in Telegram and I don't know all telegram equivalent users in Discrod. Cheers!

**Comment by OasisCoinTeam** [comment]
On telegram:
@Reeltime (Jason)
@Klaud07 (Klaud)
@neuronex (Francois)
@Dasengineer (Sergo)

**Comment by ghost** [comment]
On telegram:
@reeltime (Jason)
@Klaud07 (Klaud)
@NeuroNex (Francois)
@DASEngineer (Sergo)

**Comment by thewatchers1456** [comment]
When I get a chance I will take a look at the bitcoin talk thread and find the 5 most active users that are not already listed above.

**Comment by aaroque** [comment]
I think we're missing one of the most ACTIVE member, imho ofc, where is the nomination of Pesh#1111 ...??  he's been helping and guiding everyone on discord since the beginning. Other channels too but most of the time there.

**Comment by Klaud07** [comment]
On telegram: @thewatchers1456 (TheWatchers)

**Comment by ghost** [comment]
Thewatchers1456 has already been added to the list that's why I did not add him again mate otherwise I know he does a lot on there ^_^

**Comment by SuB1X-Coin** [comment]
Pesh, TheWatchers, Francois, aaroque, MrsMasternode and PatHeyman for me have been the biggest contributors.

**Comment by thewatchers1456** [comment]
I just finished up going through the Russian SUB1X Bitcoin Talk thread and I would like to nominate the following if they are not already added to the list. This is based completely on number of posts within the thread. 


Guardsman  189 posts
ligor               115 posts
Klaud07          91 posts 
Dasengineer  72 posts
gigaoptic        42 posts

I am currently going through the English threads now. Both the original ANN and the newer ANN

**Comment by ghost** [comment]
this stuff is getting hairy now. Users across Discord, Telegram, BTCTalk. For example, what's `Guardsman`'s discord / telegram id?

Please help me compile this list in a format like this:
Discord users with optional Telegram and BTCTalk users:
```
MrsMasternode#3394
PatHeyman#7056
PzYcO#0420
Roque#6904 (Telegram: Bugs)
TheWatchers1456#1895
Wajito#6774
Pesh#1111 (Telegram: Bunny)
```

**Comment by thewatchers1456** [comment]
@homesoft is Ligor's telegram user name.
@Igor#3514 is Ligor's discord user name.

Still waiting on a reply from Guardsman

**Comment by thewatchers1456** [comment]
Guardsman's telegram is @sergey_xxl
And discord is Guardsman#5767 

Those are the last I would like to add.

**Comment by ghost** [comment]
Closing as all winners have been paid
